Technically, my implementation works, but now the problem seems to be with the models themselves.
Radloff (model1):
Exception: org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Model configuration attribute missing from TeamCode\src\main\assets\testModel1\model.h5 archive.. For more information, see http://deeplearning4j.org/model-import-keras. try again.

Bo (model2):
Exception: org.deeplearning4j.nn.modelimport.keras.exceptions.UnsupportedKerasConfigurationException: Unsupported keras layer type Lambda. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues. try again.

Radloff(model1 attempt two)
Exception: org.deeplearning4j.nn.modelimport.keras.exceptions.InvalidKerasConfigurationException: Found weights for layer not in model (named dense_2). For more information, see http://deeplearning4j.org/model-import-keras. try again.

Also, I didn't commit the actual models b/c they were too big.